imports:
    - { resource: amf.yml }

framework:
    charset: UTF-8
    secret: ThisTokenIsNotSoSecretChangeIt
    csrf_protection: true
    router:
      resource: "%kernel.root_dir%/config/routing.yml"
    templating:
      engine: twig
    validation:
      enable_annotations: true
    session:
      default_locale: en
      lifetime: 3600
      auto_start: true

## Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%